services:
  master:
    image: postgis/postgis:17-3.3
    container_name: pg_master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=master_db
    ports:
      - "5432:5432"
    volumes:
      - master-data:/var/lib/postgresql/data
      - ./master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    command: >
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10

  replica:
    image: postgis/postgis:17-3.3
    container_name: pg_replica
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=replica_db
    ports:
      - "5433:5432"
    volumes:
      - replica-data:/var/lib/postgresql/data
      - ./replica-init.sql:/docker-entrypoint-initdb.d/replica-init.sql
    command: >
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10

volumes:
  master-data:
  replica-data: